In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/fashionmnist/t10k-labels-idx1-ubyte
/kaggle/input/fashionmnist/t10k-images-idx3-ubyte
/kaggle/input/fashionmnist/fashion-mnist_test.csv
/kaggle/input/fashionmnist/fashion-mnist_train.csv
/kaggle/input/fashionmnist/train-labels-idx1-ubyte
/kaggle/input/fashionmnist/train-images-idx3-ubyte


In [2]:
import numpy as np
from tqdm import tqdm
import pandas as pd
import random
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
import time
import os
from scipy.signal import correlate2d
from skimage.measure import block_reduce


In [8]:


class CNN:
    def __init__(self, input_size=(28, 28), num_filters=8, filter_size=3, pool_size=2, num_classes=10, learning_rate=0.01):
        self.input_size = input_size
        self.num_filters = num_filters
        self.filter_size = filter_size
        self.pool_size = pool_size
        self.num_classes = num_classes
        self.lr = learning_rate

        # Initialize filters and weights
        self.filters = np.random.randn(num_filters, filter_size, filter_size) * 0.1
        self.fc_weights = np.random.randn(num_filters * ((input_size[0] - filter_size + 1) // pool_size) * 
                                          ((input_size[1] - filter_size + 1) // pool_size), num_classes) * 0.1
        self.fc_bias = np.zeros((1, num_classes))

    def convolve2D(self, image, kernel):
        return correlate2d(image, kernel, mode='valid')

        # kernel_size = kernel.shape[0]
        # output_size = (image.shape[0] - kernel_size + 1, image.shape[1] - kernel_size + 1)
        # output = np.zeros(output_size)

        # for i in range(output_size[0]):
        #     for j in range(output_size[1]):
        #         region = image[i:i + kernel_size, j:j + kernel_size]
        #         output[i, j] = np.sum(region * kernel)

        # return output

    def max_pooling(self, feature_map, size):
        # return block_reduce(feature_map, (size, size), np.max)
        h, w = feature_map.shape
        output_size = (h // size, w // size)
        output = np.zeros(output_size)
        self.pool_cache = {}

        for i in range(output_size[0]):
            for j in range(output_size[1]):
                region = feature_map[i * size:(i + 1) * size, j * size:(j + 1) * size]
                max_val = np.max(region)
                max_pos = np.unravel_index(np.argmax(region), region.shape)
                output[i, j] = max_val
                self.pool_cache[(i, j)] = (i * size + max_pos[0], j * size + max_pos[1])  # Store relative positions

        return output

    def sigmoid(self, x):
        x = np.clip(x, -500, 500)  # Prevent overflow
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def softmax(self, x):
        exps = np.exp(x - np.max(x))
        return exps / np.sum(exps, axis=1, keepdims=True)

    def cross_entropy_loss(self, probs, label):
        probs = np.clip(probs, 1e-10, 1)  # Prevent log(0)
        return -np.log(probs[0, label])  # Corrected label indexing

    def forward(self, image):
        self.input_image = image
        self.feature_maps = np.array([self.convolve2D(image, kernel) for kernel in self.filters])
        self.sigmoid_maps = np.array([self.sigmoid(x) for x in self.feature_maps])
        self.pooled_maps = np.array([self.max_pooling(fm, self.pool_size) for fm in self.sigmoid_maps])

        self.flattened = self.pooled_maps.flatten().reshape(1, -1)
        self.scores = np.dot(self.flattened, self.fc_weights) + self.fc_bias
        self.probs = self.softmax(self.scores)

        return self.probs

    def backward(self, label):
        d_scores = self.probs.copy()  # Don't modify self.probs
        d_scores[0, label] -= 1  # Compute gradient of loss w.r.t. scores

        d_fc_weights = np.dot(self.flattened.T, d_scores)
        d_fc_bias = np.sum(d_scores, axis=0, keepdims=True)
        d_flattened = np.dot(d_scores, self.fc_weights.T)

        d_pooled = d_flattened.reshape(self.pooled_maps.shape)

        # Backprop through pooling
        d_sigmoid_maps = np.zeros_like(self.sigmoid_maps)
        for i in range(self.num_filters):
            for (py, px), (y, x) in self.pool_cache.items():
                d_sigmoid_maps[i, y, x] = d_pooled[i, py, px]  # Use stored pooling indices

        # Backprop through sigmoid
        d_feature_maps = d_sigmoid_maps * self.sigmoid_derivative(self.sigmoid_maps)

        # Backprop through convolution
        d_filters = np.zeros_like(self.filters)
        for i in range(self.num_filters):
            for y in range(self.filter_size):
                for x in range(self.filter_size):
                    region = self.input_image[y:y + d_feature_maps.shape[1], x:x + d_feature_maps.shape[2]]
                    d_filters[i, y, x] = np.sum(region * d_feature_maps[i])

        # Gradient clipping to prevent instability
        d_fc_weights = np.clip(d_fc_weights, -1, 1)
        d_fc_bias = np.clip(d_fc_bias, -1, 1)
        d_filters = np.clip(d_filters, -1, 1)

        # Update weights
        self.fc_weights -= self.lr * d_fc_weights
        self.fc_bias -= self.lr * d_fc_bias
        self.filters -= self.lr * d_filters


    def predict(self, image):
        """ Returns predicted class label """
        output = self.forward(image)
        return np.argmax(output)

    def train(self, dataset, labels, epochs=10, batch_size=32):
        num_samples = dataset.shape[0]
        history = {'loss': [], 'f1_score': [], 'training_time': []}
        
        for epoch in range(epochs):
            start_time = time.time()
            loss = 0
            num_batches = num_samples//batch_size
            all_preds = []
            all_labels = []
            
            with tqdm(total=num_batches, desc=f"Epoch {epoch + 1}/{epochs}") as pbar:
                for i in range(0, num_samples, batch_size):
                    X_batch = dataset[i:i+batch_size]
                    y_batch = labels[i:i+batch_size]
                    batch_loss = 0
            
                    for image, label in zip(X_batch, y_batch):
                        #image, label = dataset[i], labels[i]
                        output = self.forward(image)
                        batch_loss += self.cross_entropy_loss(output, label)
                        self.backward(label)

                        pred_label = np.argmax(output)
                        all_preds.append(pred_label)
                        all_labels.append(label)
                    loss+= batch_loss/len(X_batch)
                    pbar.update(1)

            avg_loss = loss / len(dataset)
            f1 = f1_score(all_labels, all_preds, average="weighted")
            epoch_time = time.time() - start_time

            history['loss'].append(avg_loss)
            history['f1_score'].append(f1)
            history['training_time'].append(epoch_time)

            print(f"Epoch {epoch + 1}/{epochs}, Loss: {avg_loss:.4f}")
        return history


    def evaluate(self, dataset, labels):
        preds = np.array([self.predict(image) for image in dataset])
        labels = np.array(labels)
        
        accuracy = np.mean(preds == labels)
        f1 = f1_score(labels, preds, average="weighted")
        conf_matrix = confusion_matrix(labels, preds)

        print(f"Accuracy: {accuracy * 100:.2f}%")
        print(f"F1 Score: {f1:.4f}")
        print(f"Confusion Matrix:\n{conf_matrix}")

        return {"accuracy": accuracy, "f1_score": f1, "confusion_matrix": conf_matrix}



In [4]:
# Load MNIST dataset (CSV format)
train_data = pd.read_csv('/kaggle/input/fashionmnist/fashion-mnist_train.csv')
test_data = pd.read_csv('/kaggle/input/fashionmnist/fashion-mnist_test.csv')
train_data['label'].value_counts()

label
2    6000
9    6000
6    6000
0    6000
3    6000
4    6000
5    6000
8    6000
7    6000
1    6000
Name: count, dtype: int64

In [11]:

# Split features and labels
X_train = train_data.iloc[0:10000, 1:].values  # Pixels
y_train = train_data.iloc[0:10000, 0].values   # Labels

X_test = test_data.iloc[0:10000, 1:].values
y_test = test_data.iloc[0:10000, 0].values

# Normalize pixel values (0 to 1)
X_train = X_train / 255.0
X_test = X_test / 255.0

# Reshape to (28, 28) for CNN input
X_train = X_train.reshape(-1, 28, 28)
X_test = X_test.reshape(-1, 28, 28)

# Define number of classes
num_classes = 10

# One-hot encode labels
def one_hot_encode(y, num_classes):
    encoded = np.zeros((len(y), num_classes))
    encoded[np.arange(len(y)), y] = 1
    return encoded

y_train_one_hot = one_hot_encode(y_train, num_classes)
y_test_one_hot = one_hot_encode(y_test, num_classes)




In [12]:

cnn = CNN(input_size=(28, 28), num_filters=8, filter_size=3, pool_size=2, num_classes=10, learning_rate=0.01)

# Train CNN on MNIST
history = cnn.train(X_train, y_train, epochs=10)  # Using only 5000 samples for faster training



Epoch 1/10: 313it [03:05,  1.68it/s]                         


Epoch 1/10, Loss: 0.0289


Epoch 2/10: 313it [03:05,  1.69it/s]                         


Epoch 2/10, Loss: 0.0197


Epoch 3/10: 313it [03:04,  1.70it/s]                         


Epoch 3/10, Loss: 0.0180


Epoch 4/10: 313it [03:04,  1.70it/s]                         


Epoch 4/10, Loss: 0.0169


Epoch 5/10: 313it [03:01,  1.72it/s]                         


Epoch 5/10, Loss: 0.0160


Epoch 6/10: 313it [03:03,  1.71it/s]                         


Epoch 6/10, Loss: 0.0153


Epoch 7/10: 313it [03:03,  1.70it/s]                         


Epoch 7/10, Loss: 0.0147


Epoch 8/10: 313it [03:03,  1.71it/s]                         


Epoch 8/10, Loss: 0.0142


Epoch 9/10: 313it [03:03,  1.71it/s]                         


Epoch 9/10, Loss: 0.0138


Epoch 10/10: 313it [03:05,  1.69it/s]                         

Epoch 10/10, Loss: 0.0134


In [10]:
performance = cnn.evaluate(X_test, y_test)

Accuracy: 81.78%
F1 Score: 0.8184
Confusion Matrix:
[[366   1   5  46   0   1  62   0  21   0]
 [  0 457   0  23   0   0   9   0   1   0]
 [  3   0 302   9  55   2 110   0   9   0]
 [  3   2   1 468   3   0  27   0   3   0]
 [  0   3  39  43 324   0  96   0   1   0]
 [  0   0   0   0   0 428   0  40   7  15]
 [ 63   1  26  39  17   2 354   1  16   0]
 [  0   0   0   0   0  12   0 450   1   8]
 [  0   1   0   1   1   0   8   5 492   0]
 [  0   0   0   0   0   8   0  61   0 448]]
